Repository homebaseio/datalog-console, pull requests merged in 2021-06, with the labels that each got.

#16 fix: typo in query examples
  shells/chrome/manifest.edn
  src/main/datalog_console/components/query.cljs
Labels: bug

#19 feat(integrations): move handlers into an integrations library
  .github/pull_request_template.md
  .gitignore
  README.md
  deps.edn
  package.json
  pom.xml
  src/dev/datalog_console/workspaces/chrome/extension_cards.cljs
  src/dev/datalog_console/workspaces/chrome/formatter_cards.cljs
  src/dev/datalog_console/workspaces/client_cards.cljs
  src/dev/datalog_console/workspaces/demo_cards.cljs
  src/dev/datalog_console/workspaces/entity_cards.cljs
  src/dev/datalog_console/workspaces/query_cards.cljs
  src/dev/datalog_console/workspaces/schema_cards.cljs
  src/dev/datalog_console/workspaces/tree_table_cards.cljs
  src/main/datalog_console/client.cljs
  src/main/datalog_console/components/entities.cljs
  src/main/datalog_console/components/entity.cljs
  src/main/datalog_console/components/query.cljs
  src/main/datalog_console/components/schema.cljs
  src/main/datalog_console/components/tree_table.cljs
  src/main/datalog_console/integrations/datascript.cljs
  src/main/datalog_console/lib/chromestorage.cljs
  src/main/datalog_console/lib/localstorage.cljs
Labels: enhancement

#20 Add no-doc
  src/main/datalog_console/chrome/extension/background/main.cljs
  src/main/datalog_console/chrome/extension/content_script/main.cljs
  src/main/datalog_console/chrome/extension/devtool/main.cljs
  src/main/datalog_console/chrome/formatters.cljs
Labels: documentation

#18 feat(chrome extension): add transact component
  deps.edn
  package.json
  pom.xml
  shells/chrome/manifest.edn
  src/dev/datalog_console/workspaces/chrome/extension_cards.cljs
  src/dev/datalog_console/workspaces/chrome/formatter_cards.cljs
  src/dev/datalog_console/workspaces/client_cards.cljs
  src/dev/datalog_console/workspaces/entity_cards.cljs
  src/dev/datalog_console/workspaces/query_cards.cljs
  src/dev/datalog_console/workspaces/transact_cards.cljs
  src/dev/datalog_console/workspaces/workspace_db_conn.cljs
  src/main/datalog_console/client.cljs
  src/main/datalog_console/components/feature_flag.cljs
  src/main/datalog_console/components/query.cljs
  src/main/datalog_console/components/transact.cljs
  src/main/datalog_console/integrations/datascript.cljs
  src/main/datalog_console/lib/version.cljc
Labels: enhancement
